const express = require('express');
const path = require('path');
const urlRoute = require("./routes/url");
const staticRoute=require('./routes/staticRoutes');
const userRoute=require('./routes/user');
const { connectToMongoDB } = require("./connect");
const cookieParser = require('cookie-parser');
const { restrictToLoggedInUser } = require('./controllers/middleware/auth');
const app = express();
const PORT = 8000;
connectToMongoDB('mongodb://localhost:27017/short-url').then(() => console.log(`mongoDB is connected`));
app.set('view engine' ,'ejs');
app.set("views",path.resolve('./views'));
app.use(express.json());
app.use(cookieParser());
app.use(express.urlencoded({extended:false}));
app.use('/url',restrictToLoggedInUser, urlRoute);
app.use('/user',userRoute);
app.use('/',staticRoute);
app.listen(PORT, () => { console.log(`server started at ${PORT}`) });